version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    networks:
      - backend-network

  bookstore-api:
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    container_name: bookstore-api
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
